export default {
  INTRO: "INTRO",
  LOG_IN: "LOG_IN",
  SIGN_UP: "SIGN_UP",
  SIGN_UP_PROCESS: "SIGN_UP_PROCESS",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  AUTH_NAV: "AUTH_NAV",
  BOTTOM_TAB_NAV: "BOTTOM_TAB_NAV",
  HOME: "HOME",
};
